## Упражнения по библиотеке Numpy

In [1]:
import numpy as np
import numpy.random as rand
import time
import scipy.spatial.distance

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
a = np.random.randint(10, size=(10))
print("Массив до замены")
print(a)
for i in range(len(a)):
    if a[i] > 3 and a[i] < 8:
        a[i] *= -1

print("Массив после замены")
print(a)

Массив до замены
[3 8 0 5 8 2 4 7 3 4]
Массив после замены
[ 3  8  0 -5  8  2 -4 -7  3 -4]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
a = np.random.randint(100, size=(10))
print(f"массив до замены {a}")
a[np.argmax(a)] = 0
print(f"массив после замены {a}")

массив до замены [99 32 22 67 59 66  9 42 10 73]
массив после замены [ 0 32 22 67 59 66  9 42 10 73]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7,8,9], [10,11,12]])
a=b.flatten()
rows, cols = b.shape
for i in range(rows):
    for t in range(len(b[0]), len(a)):
        print(f"{a[i]}{a[t]} ", end="")
    print()

14 15 16 17 18 19 110 111 112 
24 25 26 27 28 29 210 211 212 
34 35 36 37 38 39 310 311 312 
44 45 46 47 48 49 410 411 412 


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
#элементы из каждой строки в B значит хотя бы один элемент из каждой строки?
a = np.random.randint(10, size=(24)).reshape((8,3))
b = np.random.randint(10,size=(4)).reshape((2,2))
print(a)
print()
print(b)
for i in a:
    str_1 = False
    str_2 = False
    for j in i:
        if j in b[0]:
            str_1 = True
        if j in b[1]:
            str_2 = True
    if str_1 and str_2:
        print(f"podhodit stroka {i}")

[[5 0 6]
 [4 2 4]
 [1 1 1]
 [1 0 3]
 [0 1 8]
 [5 1 1]
 [6 7 1]
 [1 3 5]]

[[2 3]
 [5 0]]
podhodit stroka [1 0 3]
podhodit stroka [1 3 5]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
a = np.random.randint(10, size=(30)).reshape((10,3))
a[3] = np.array([1,1,1])
a[7] = np.array([0,0,0])
udal = []
print(a)
for i,k in enumerate(a):
    if k[0]==k[1] and k[1]==k[2]:
        udal.append(i)
for i in udal[::-1]:
    a = np.delete(a,i, axis = 0)
a

[[5 4 1]
 [1 0 6]
 [1 6 6]
 [1 1 1]
 [8 6 0]
 [2 9 5]
 [5 3 1]
 [0 0 0]
 [0 4 1]
 [2 2 2]]


array([[5, 4, 1],
       [1, 0, 6],
       [1, 6, 6],
       [8, 6, 0],
       [2, 9, 5],
       [5, 3, 1],
       [0, 4, 1]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
a = np.array([[1,2,3,4],[1,2,3,4],[6,7,8,9],[1,2,3,4],[1,2,3,4],[3,3,3,3],[4,4,4,4],[3,3,3,3],[4,4,4,4]])
udal = []
k = 1
print(a)
rows, cols = a.shape
for i in a:
    for j in range (k,rows):
        if (i == a[j] ).all() and j not in udal:
            udal.append(j)
    k +=1 
for i in udal[::-1]:
    a = np.delete(a,i, axis = 0)
a

[[1 2 3 4]
 [1 2 3 4]
 [6 7 8 9]
 [1 2 3 4]
 [1 2 3 4]
 [3 3 3 3]
 [4 4 4 4]
 [3 3 3 3]
 [4 4 4 4]]


array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [8]:
matrix = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
pr = 1
for i in range(len(matrix[0])):
    if matrix[i][i]!=0:
        pr *= matrix[i][i]
print(pr)


3


In [9]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
np.prod(np.diagonal(X)[np.diagonal(X)[:]>0])

3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
x = [1,2,2,4]
y = [4,2,1,2]
x.sort()
y.sort()
b = True
if len(x) == len(y):
    for i in range(len(x)):
        if x[i]!=y[i]:
            b = False
else:
    b =  False
print(b)

True


In [11]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print(True if np.array_equal(np.sort(x),np.sort(y)) else False)

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [12]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max = min(x)
for i in range(1, len(x)):
    if x[i-1] == 0 and x[i]> max:
        max = x[i]
print(max)

5


In [13]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
y = np.where(x == 0)
print(x[1:][y[0][:-1]].max())

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [14]:
x = [2,2,2,3,3,3,5]
elements = []
for i in x:
    if i not in elements:
        elements.append(i)
print(elements)
ammount = [0 for i in range(len(elements))]
for i in range(len(elements)):
    for j in x:
        if elements[i] == j:
            ammount[i] +=1
print(ammount)

[2, 3, 5]
[3, 3, 1]


In [15]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
uniq,counts = np.unique(x, return_counts=True)
print(uniq,counts)

[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [16]:
x = [0,0,0]
y = [3,3,3]
rasst = 0
start_time = time.time()
for i in range(3):
    rasst += ((y[i]-x[i])**2)
print(float(rasst**0.5))
print(time.time() - start_time)


5.196152422706632
0.0010035037994384766


In [17]:
x = np.array([0,0,0])
y = np.array([3,3,3])
start_time = time.time()
razn = np.square(y - x)
print(np.sqrt(np.sum(razn)))
print(time.time() - start_time)

5.196152422706632
0.0


In [18]:
x = np.array([[0,0,0]])
y = np.array([[3,3,3]])
start_time = time.time()
print(scipy.spatial.distance.cdist(x, y))
print(time.time() - start_time)

[[5.19615242]]
0.0


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [19]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [20]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [21]:
average_calories = np.average(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [22]:
calories_stats_sorted = np.sort(calorie_stats)
calories_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [23]:
median_calories = np.median(calories_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [24]:
nth_percentile = 0
b = True
for i in range(1,101):
    if b:
        nth_percentile = i
        if np.percentile(calories_stats_sorted, i) > 60:
            b = False
    if i %10 == 0:
        print(f"при процентиле {i} калории равны {int(np.percentile(calories_stats_sorted, i))}")

print(nth_percentile)

при процентиле 10 калории равны 90
при процентиле 20 калории равны 100
при процентиле 30 калории равны 100
при процентиле 40 калории равны 110
при процентиле 50 калории равны 110
при процентиле 60 калории равны 110
при процентиле 70 калории равны 110
при процентиле 80 калории равны 120
при процентиле 90 калории равны 124
при процентиле 100 калории равны 160
4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [25]:
position = 0
for i,k in enumerate(calories_stats_sorted):
    if k >60 :
        position = i
        break
more_calories = len(calories_stats_sorted[i:])/len(calories_stats_sorted)
print(more_calories*100, '%')

96.1038961038961 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [26]:
calorie_std = np.std(calories_stats_sorted)
print(calorie_std)

19.35718533390827


Эта величина показывет, что низкая калорийность хлопьев не просто небольшое отклонение от средней, а то, чем компания может гордиться

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Я считаю, что компании стоит сделать упор на низкую калорийность своих хлопьев, так как полученные данные демонстрируют
уверенное превосходство хлопьев CrunchieMunchies на поприще еды низкой калорийности по сравнению с конкурентами.